services:
  test:
    image: node:18-alpine
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CI=true
      - TEST_TYPE=unit
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        npm install --legacy-peer-deps &&
        make test-all
