services:
  # API service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valorant-map-picker-backend
    restart: unless-stopped
    environment:
      - VALOMAP_SERVER_PORT=3000
      - VALOMAP_LOGGING_LEVEL=info
      - VALOMAP_LOGGING_FORMAT=json
      - VALOMAP_SECURITY_ALLOWED_ORIGINS=https://valomap.com
    volumes:
      - ./backend/config/config.yaml:/etc/valorant-map-picker/config.yaml:ro
      - ./images-cache:/home/appuser/images-cache
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.valomap-api.rule=Host(`valomap.com`) && PathPrefix(`/map`)"
      - "traefik.http.routers.valomap-api.entrypoints=websecure"
      - "traefik.http.routers.valomap-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.valomap-api.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.valomap-api-stripprefix.stripprefix.prefixes=/map"
      - "traefik.http.middlewares.valomap-api-addprefix.addprefix.prefix=/api/v1/map"
      - "traefik.http.routers.valomap-api.middlewares=valomap-api-stripprefix,valomap-api-addprefix"
      - "traefik.http.routers.valomap-cache.rule=Host(`valomap.com`) && PathPrefix(`/api/cache`)"
      - "traefik.http.routers.valomap-cache.entrypoints=websecure"
      - "traefik.http.routers.valomap-cache.tls.certresolver=letsencrypt"
      - "traefik.http.services.valomap-cache.loadbalancer.server.port=3000"
      - "traefik.http.routers.valomap-cache.priority=10"

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: valorant-map-picker-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.valomap-frontend.rule=Host(`valomap.com`)"
      - "traefik.http.routers.valomap-frontend.entrypoints=websecure"
      - "traefik.http.routers.valomap-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.valomap-frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
      - "traefik.http.routers.valomap-frontend.priority=1"

  # Traefik reverse proxy with Let's Encrypt
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/acme.json:/acme.json
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.valomap.com`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$70hN10X7$$3QbzMaVnA3pagO1OJl1o90"  # Replace with your hashed password
      - "traefik.http.routers.traefik.middlewares=traefik-auth"

networks:
  web:
    external: true
