services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./coverage_report:/app/coverage_report
    command: ["make", "test"]

  test-unit:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: ["make", "test-unit"]

  test-coverage:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./coverage_report:/app/coverage_report
    command: ["make", "test-coverage"]

  test-benchmark:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./benchmark_results.txt:/app/benchmark_results.txt
    command: ["make", "test-benchmark"]

  test-race:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: ["make", "test-race"]
