FROM golang:1.24-alpine

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache make git ca-certificates tzdata gcc musl-dev bash && \
    update-ca-certificates

# Copy the source code
COPY . .

# Download dependencies
RUN go mod download

# ENTRYPOINT ["/usr/bin/make"]

# CMD [ "test" ]
