## Traefik Configuration

# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# API and dashboard configuration
api:
  dashboard: true
  insecure: false

# Entry points configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Providers configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: web
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Let's Encrypt configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: "qq3025566@gmail.com"
      storage: "acme.json"
      keyType: EC384
      httpChallenge:
        entryPoint: web

# Log configuration
log:
  level: INFO
  format: json

# Access log configuration
accessLog:
  format: json

# Metrics configuration (optional)
metrics:
  prometheus:
    entryPoint: metrics
